menu:
- {name: 'about_me', url: '/about_me'}
- {name: 'research', url: '/research_page'}
- {name: 'publications', url:'/papers'}
- {name: 'CV', url: '/assets/crehmann_CV.pdf'}

etc:
- {name: 'aeg', url: '/aeg_page'}
